using AspMVCECommerce.Models;

namespace AspMVCECommerce.Utility
{
    public static class CheckOutUtility
    {
        public static int AddCheckOut(CheckOut checkOut, ApplicationDbContext context)
        {

            var tempCustomAddress = checkOut.CustomAddress;
            var tempShippingAddress = checkOut.ShippingAddress;


            int customAddressId = CustomAddressUtility.AddCustomAddress(tempCustomAddress, context);
            checkOut.CustomAddressId = customAddressId;

            int? shippingAddress2Id = null;

            if (!string.IsNullOrEmpty(tempShippingAddress.RecipientName))
            {
                shippingAddress2Id = ShippingAddress2Utility.AddShippingAddress2(tempShippingAddress, context);
                checkOut.ShippingAddress2Id = shippingAddress2Id;
            }

            checkOut.CustomAddress = null;
            checkOut.ShippingAddress = null;
            checkOut.CheckOutId = 0;

            context.CheckOuts.Add(checkOut);
            context.SaveChanges();

            return checkOut.CheckOutId;
        }


        //public static string GetCountryNameByCode(string code)
        //{
        //    var countries = new Dictionary<string, string>(){
        //                { "ALBANIA","AL"},
        //                { "ALGERIA","DZ"},
        //                { "ANDORRA","AD"},
        //                { "ANGOLA","AO"},
        //                { "ANGUILLA","AI"},
        //                { "ANTIGUA & BARBUDA","AG"},
        //                { "ARGENTINA","AR"},
        //                { "ARMENIA","AM"},
        //                { "ARUBA","AW"},
        //                { "AUSTRALIA","AU"},
        //                { "AUSTRIA","AT"},
        //                { "AZERBAIJAN","AZ"},
        //                { "BAHAMAS","BS"},
        //                { "BAHRAIN","BH"},
        //                { "BARBADOS","BB"},
        //                { "BELARUS","BY"},
        //                { "BELGIUM","BE"},
        //                { "BELIZE","BZ"},
        //                { "BENIN","BJ"},
        //                { "BERMUDA","BM"},
        //                { "BHUTAN","BT"},
        //                { "BOLIVIA","BO"},
        //                { "BOSNIA & HERZEGOVINA","BA"},
        //                { "BOTSWANA","BW"},
        //                { "BRAZIL","BR"},
        //                { "BRITISH VIRGIN ISLANDS","VG"},
        //                { "BRUNEI","BN"},
        //                { "BULGARIA","BG"},
        //                { "BURKINA FASO","BF"},
        //                { "BURUNDI","BI"},
        //                { "CAMBODIA","KH"},
        //                { "CAMEROON","CM"},
        //                { "CANADA","CA"},
        //                { "CAPE VERDE","CV"},
        //                { "CAYMAN ISLANDS","KY"},
        //                { "CHAD","TD"},
        //                { "CHILE","CL"},
        //                { "CHINA","C2"},
        //                { "COLOMBIA","CO"},
        //                { "COMOROS","KM"},
        //                { "CONGO-BRAZZAVILLE","CG"},
        //                { "CONGO-KINSHASA","CD"},
        //                { "COOK ISLANDS","CK"},
        //                { "COSTA RICA","CR"},
        //                { "CÔTE D’IVOIRE","CI"},
        //                { "CROATIA","HR"},
        //                { "CYPRUS","CY"},
        //                { "CZECH REPUBLIC","CZ"},
        //                { "DENMARK","DK"},
        //                { "DJIBOUTI","DJ"},
        //                { "DOMINICA","DM"},
        //                { "DOMINICAN REPUBLIC","DO"},
        //                { "ECUADOR","EC"},
        //                { "EGYPT","EG"},
        //                { "EL SALVADOR","SV"},
        //                { "ERITREA","ER"},
        //                { "ESTONIA","EE"},
        //                { "ETHIOPIA","ET"},
        //                { "FALKLAND ISLANDS","FK"},
        //                { "FAROE ISLANDS","FO"},
        //                { "FIJI","FJ"},
        //                { "FINLAND","FI"},
        //                { "FRANCE","FR"},
        //                { "FRENCH GUIANA","GF"},
        //                { "FRENCH POLYNESIA","PF"},
        //                { "GABON","GA"},
        //                { "GAMBIA","GM"},
        //                { "GEORGIA","GE"},
        //                { "GERMANY","DE"},
        //                { "GIBRALTAR","GI"},
        //                { "GREECE","GR"},
        //                { "GREENLAND","GL"},
        //                { "GRENADA","GD"},
        //                { "GUADELOUPE","GP"},
        //                { "GUATEMALA","GT"},
        //                { "GUINEA","GN"},
        //                { "GUINEA-BISSAU","GW"},
        //                { "GUYANA","GY"},
        //                { "HONDURAS","HN"},
        //                { "HONG KONG SAR CHINA","HK"},
        //                { "HUNGARY","HU"},
        //                { "ICELAND","IS"},
        //                { "INDIA","IN"},
        //                { "INDONESIA","ID"},
        //                { "IRELAND","IE"},
        //                { "ISRAEL","IL"},
        //                { "ITALY","IT"},
        //                { "JAMAICA","JM"},
        //                { "JAPAN","JP"},
        //                { "JORDAN","JO"},
        //                { "KAZAKHSTAN","KZ"},
        //                { "KENYA","KE"},
        //                { "KIRIBATI","KI"},
        //                { "KUWAIT","KW"},
        //                { "KYRGYZSTAN","KG"},
        //                { "LAOS","LA"},
        //                { "LATVIA","LV"},
        //                { "LESOTHO","LS"},
        //                { "LIECHTENSTEIN","LI"},
        //                { "LITHUANIA","LT"},
        //                { "LUXEMBOURG","LU"},
        //                { "MACEDONIA","MK"},
        //                { "MADAGASCAR","MG"},
        //                { "MALAWI","MW"},
        //                { "MALAYSIA","MY"},
        //                { "MALDIVES","MV"},
        //                { "MALI","ML"},
        //                { "MALTA","MT"},
        //                { "MARSHALL ISLANDS","MH"},
        //                { "MARTINIQUE","MQ"},
        //                { "MAURITANIA","MR"},
        //                { "MAURITIUS","MU"},
        //                { "MAYOTTE","YT"},
        //                { "MEXICO","MX"},
        //                { "MICRONESIA","FM"},
        //                { "MOLDOVA","MD"},
        //                { "MONACO","MC"},
        //                { "MONGOLIA","MN"},
        //                { "MONTENEGRO","ME"},
        //                { "MONTSERRAT","MS"},
        //                { "MOROCCO","MA"},
        //                { "MOZAMBIQUE","MZ"},
        //                { "NAMIBIA","NA"},
        //                { "NAURU","NR"},
        //                { "NEPAL","NP"},
        //                { "NETHERLANDS","NL"},
        //                { "NEW CALEDONIA","NC"},
        //                { "NEW ZEALAND","NZ"},
        //                { "NICARAGUA","NI"},
        //                { "NIGER","NE"},
        //                { "NIGERIA","NG"},
        //                { "NIUE","NU"},
        //                { "NORFOLK ISLAND","NF"},
        //                { "NORWAY","NO"},
        //                { "OMAN","OM"},
        //                { "PALAU","PW"},
        //                { "PANAMA","PA"},
        //                { "PAPUA NEW GUINEA","PG"},
        //                { "PARAGUAY","PY"},
        //                { "PERU","PE"},
        //                { "PHILIPPINES","PH"},
        //                { "PITCAIRN ISLANDS","PN"},
        //                { "POLAND","PL"},
        //                { "PORTUGAL","PT"},
        //                { "QATAR","QA"},
        //                { "RÉUNION","RE"},
        //                { "ROMANIA","RO"},
        //                { "RUSSIA","RU"},
        //                { "RWANDA","RW"},
        //                { "SAMOA","WS"},
        //                { "SAN MARINO","SM"},
        //                { "SÃO TOMÉ & PRÍNCIPE","ST"},
        //                { "SAUDI ARABIA","SA"},
        //                { "SENEGAL","SN"},
        //                { "SERBIA","RS"},
        //                { "SEYCHELLES","SC"},
        //                { "SIERRA LEONE","SL"},
        //                { "SINGAPORE","SG"},
        //                { "SLOVAKIA","SK"},
        //                { "SLOVENIA","SI"},
        //                { "SOLOMON ISLANDS","SB"},
        //                { "SOMALIA","SO"},
        //                { "SOUTH AFRICA","ZA"},
        //                { "SOUTH KOREA","KR"},
        //                { "SPAIN","ES"},
        //                { "SRI LANKA","LK"},
        //                { "ST. HELENA","SH"},
        //                { "ST. KITTS & NEVIS","KN"},
        //                { "ST. LUCIA","LC"},
        //                { "ST. PIERRE & MIQUELON","PM"},
        //                { "ST. VINCENT & GRENADINES","VC"},
        //                { "SURINAME","SR"},
        //                { "SVALBARD & JAN MAYEN","SJ"},
        //                { "SWAZILAND","SZ"},
        //                { "SWEDEN","SE"},
        //                { "SWITZERLAND","CH"},
        //                { "TAIWAN","TW"},
        //                { "TAJIKISTAN","TJ"},
        //                { "TANZANIA","TZ"},
        //                { "THAILAND","TH"},
        //                { "TOGO","TG"},
        //                { "TONGA","TO"},
        //                { "TRINIDAD & TOBAGO","TT"},
        //                { "TUNISIA","TN"},
        //                { "TURKMENISTAN","TM"},
        //                { "TURKS & CAICOS ISLANDS","TC"},
        //                { "TUVALU","TV"},
        //                { "UGANDA","UG"},
        //                { "UKRAINE","UA"},
        //                { "UNITED ARAB EMIRATES","AE"},
        //                { "UNITED KINGDOM","GB"},
        //                { "UNITED STATES","US"},
        //                { "URUGUAY","UY"},
        //                { "VANUATU","VU"},
        //                { "VATICAN CITY","VA"},
        //                { "VENEZUELA","VE"},
        //                { "VIETNAM","VN"},
        //                { "WALLIS & FUTUNA","WF"},
        //                { "YEMEN","YE"},
        //                { "ZAMBIA","ZM"},
        //                { "ZIMBABWE","ZW"} 
        //    };


        //    return countries.Where(p => p.Value.Contains(code)).FirstOrDefault().Key;
        //}

    }
}